from typing import List, Optional
from decimal import Decimal
from fastapi import APIRouter, Depends, HTTPException, Header, status, Query
from sqlalchemy.orm import Session

from .. import models, schemas
from ..database import get_db
from ..core.dependencies import get_current_user, check_transaction_cancellation_permission
from ..services.inventory_engine import InventoryTransactionEngine
from ..services.reference_service import generate_transaction_reference
from ..models.transaction import TransactionType, TransactionStatus

router = APIRouter(prefix="/transactions", tags=["Transactions & Inventory Engine"])


def _serialize_tx(tx: models.Transaction) -> schemas.TransactionOut:
    items = []
    for it in tx.items:
        items.append(
            schemas.TransactionItemOut(
                id=it.id,
                transaction_id=it.transaction_id,
                product_id=it.product_id,
                quantity=float(it.quantity),
                adjustment_delta=float(it.adjustment_delta) if it.adjustment_delta is not None else None,
                product_name=it.product.name if it.product else None,
                sku=it.product.sku if it.product else None,
            )
        )
    return schemas.TransactionOut(
        id=tx.id,
        reference=tx.reference,
        type=str(tx.type.value if hasattr(tx.type, "value") else tx.type),
        status=str(tx.status.value if hasattr(tx.status, "value") else tx.status),
        source_location_id=tx.source_location_id,
        destination_location_id=tx.destination_location_id,
        party_name=tx.party_name,
        contact=tx.contact,
        delivery_address=tx.delivery_address,
        schedule_date=tx.schedule_date,
        reason=tx.reason,
        created_by=tx.created_by,
        validated_by=tx.validated_by,
        created_at=tx.created_at,
        updated_at=tx.updated_at,
        validated_at=tx.validated_at,
        canceled_at=tx.canceled_at,
        items=items,
    )


@router.get("", response_model=List[schemas.TransactionOut])
def list_transactions(
    type: Optional[str] = Query(None, description="Filter by type: RECEIPT, DELIVERY, TRANSFER, ADJUSTMENT"),
    status: Optional[str] = Query(None, description="Filter by status: DRAFT, WAITING, READY, DONE, CANCELED"),
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    """
    Section 14 & 6: Unified transactions query.
    """
    query = db.query(models.Transaction)
    if type:
        query = query.filter(models.Transaction.type == type.upper())
    if status:
        query = query.filter(models.Transaction.status == status.upper())
    txs = query.order_by(models.Transaction.id.desc()).all()
    return [_serialize_tx(t) for t in txs]


@router.get("/{transaction_id}", response_model=schemas.TransactionOut)
def get_transaction(
    transaction_id: int,
    db: Session = Depends(get_db),
    _: models.User = Depends(get_current_user),
):
    tx = db.query(models.Transaction).filter(models.Transaction.id == transaction_id).first()
    if not tx:
        raise HTTPException(status_code=404, detail="Transaction not found")
    return _serialize_tx(tx)


@router.post("", response_model=schemas.TransactionOut, status_code=status.HTTP_201_CREATED)
def create_transaction(
    payload: schemas.TransactionIn,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user),
):
    """
    Section 14: ONE unified transaction model.
    Section 41: References generated by backend using sequences (WH/IN/0001, WH/OUT/0001, etc.).
    """
    # Normalize type
    tx_type_str = payload.type.strip().upper()
    try:
        tx_type = TransactionType(tx_type_str)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid transaction type '{payload.type}'. Must be RECEIPT, DELIVERY, TRANSFER, or ADJUSTMENT",
        )

    # Validate location requirements per type
    if tx_type == TransactionType.RECEIPT and not payload.destination_location_id:
        raise HTTPException(status_code=400, detail="Receipt requires destination_location_id")
    if tx_type == TransactionType.DELIVERY and not payload.source_location_id:
        raise HTTPException(status_code=400, detail="Delivery requires source_location_id")
    if tx_type == TransactionType.TRANSFER:
        if not payload.source_location_id or not payload.destination_location_id:
            raise HTTPException(status_code=400, detail="Transfer requires both source and destination locations")
        if payload.source_location_id == payload.destination_location_id:
            raise HTTPException(status_code=400, detail="Source and destination locations cannot be identical")
    if tx_type == TransactionType.ADJUSTMENT:
        if not payload.source_location_id and not payload.destination_location_id:
            raise HTTPException(status_code=400, detail="Adjustment requires a location")
        if not payload.reason or not payload.reason.strip():
            raise HTTPException(status_code=400, detail="Adjustment reason is required (Section 42)")

    # Section 41: Generate backend reference
    wh_code = payload.warehouse_code or "WH"
    reference = generate_transaction_reference(db, tx_type, wh_code)

    tx = models.Transaction(
        reference=reference,
        type=tx_type,
        status=TransactionStatus.DRAFT,
        source_location_id=payload.source_location_id,
        destination_location_id=payload.destination_location_id,
        party_name=payload.party_name,
        contact=payload.contact,
        delivery_address=payload.delivery_address,
        schedule_date=payload.schedule_date,
        reason=payload.reason,
        created_by=user.id,
    )
    db.add(tx)
    db.flush()

    for item in payload.items:
        it = models.TransactionItem(
            transaction_id=tx.id,
            product_id=item.product_id,
            quantity=Decimal(str(item.quantity)),
            adjustment_delta=Decimal(str(item.adjustment_delta)) if item.adjustment_delta is not None else None,
        )
        db.add(it)

    db.commit()
    db.refresh(tx)
    return _serialize_tx(tx)


@router.post("/{transaction_id}/prepare", response_model=schemas.TransactionOut)
def prepare_transaction(
    transaction_id: int,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user),
):
    """
    Section 16 & 17:
    Check stock availability and reserve quantity for Delivery.
    DRAFT -> READY (if sufficient stock available; stock.reserved += qty)
    DRAFT -> WAITING (if insufficient stock; no stock impact, no reservation)
    """
    engine = InventoryTransactionEngine(db)
    tx = engine.prepare_delivery(transaction_id, user)
    return _serialize_tx(tx)


@router.post("/{transaction_id}/validate", response_model=schemas.TransactionOut)
def validate_transaction_endpoint(
    transaction_id: int,
    idempotency_key: Optional[str] = Header(None, alias="Idempotency-Key"),
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user),
):
    """
    Section 18: Authoritative 13-step Inventory Transaction Engine.
    Section 40: Protected by Idempotency-Key against double taps, network retries.
    A transaction must never mutate inventory twice.
    """
    engine = InventoryTransactionEngine(db)
    tx = engine.validate_transaction(
        transaction_id=transaction_id,
        user=user,
        idempotency_key=idempotency_key,
    )
    return _serialize_tx(tx)


@router.post("/{transaction_id}/cancel", response_model=schemas.TransactionOut)
def cancel_transaction_endpoint(
    transaction_id: int,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user),
):
    """
    Section 16, 17, & 6: Cancel transaction.
    Staff can cancel their own transactions; Managers can cancel any transaction.
    Releases reserved stock if canceled from READY.
    """
    tx = db.query(models.Transaction).filter(models.Transaction.id == transaction_id).first()
    if not tx:
        raise HTTPException(status_code=404, detail="Transaction not found")

    # Section 6 RBAC check
    check_transaction_cancellation_permission(tx.created_by, user)

    engine = InventoryTransactionEngine(db)
    canceled_tx = engine.cancel_transaction(transaction_id, user)
    return _serialize_tx(canceled_tx)
